apiVersion: v1
data:
  PHP_TZ: America/Sao_Paulo
  ENABLE_WEB_ACCESS_LOG: "true"
  ZBX_ENABLE_SNMP_TRAPS: "true"
  ZBX_ACTIVE_ALLOW: "true"
  ZBX_HOSTNAME: {{.Chart.Name }}-agent
  ZBX_METADATA: Linux
  ZBX_SERVER_HOST: {{.Chart.Name }}-server.{{ .Release.Namespace }}.svc.cluster.local
  DB_SERVER_HOST: {{.Chart.Name }}-mariadb.{{ .Release.Namespace }}.svc.cluster.local
  DB_SERVER_PORT: "3306"
  MARIADB_DATABASE: "{{.Chart.Name }}"
kind: ConfigMap
metadata:
  labels:
    service: {{.Chart.Name }}
  name: {{.Chart.Name }}-agent
  namespace: {{ .Release.Namespace }}
