apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    com.zabbix.company: {{ .Values.companyName }}
    com.zabbix.component: {{.Chart.Name }}-agent
    com.zabbix.description: Zabbix Agent
    com.zabbix.os: alpine
  labels:
    service: {{.Chart.Name }}-agent
  name: {{.Chart.Name }}-agent
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: {{.Chart.Name }}-agent
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        com.zabbix.company: {{ .Values.companyName }}
        com.zabbix.component: {{.Chart.Name }}-agent
        com.zabbix.description: Zabbix Agent
        com.zabbix.os: alpine
      labels:
        service: {{.Chart.Name }}-agent
    spec:
      containers:
        - env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MARIADB_ROOT_PASSWORD
                  name: zabbix
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: MARIADB_USER
                  name: zabbix
            - name: DB_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_SERVER_HOST
                  name: {{.Chart.Name }}-agent
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MARIADB_DATABASE
                  name: {{.Chart.Name }}-agent
            - name: PHP_TZ
              valueFrom:
                configMapKeyRef:
                  key: PHP_TZ
                  name: {{.Chart.Name }}-agent
            - name: ZBX_ENABLE_SNMP_TRAPS
              valueFrom:
                configMapKeyRef:
                  key: ZBX_ENABLE_SNMP_TRAPS
                  name: {{.Chart.Name }}-agent
            - name: ZBX_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: ZBX_HOSTNAME
                  name: {{.Chart.Name }}-agent
            - name: ZBX_ACTIVE_ALLOW
              valueFrom:
                configMapKeyRef:
                  key: ZBX_ACTIVE_ALLOW
                  name: {{.Chart.Name }}-agent
            - name: ZBX_METADATA
              valueFrom:
                configMapKeyRef:
                  key: ZBX_METADATA
                  name: {{.Chart.Name }}-agent
            - name: ZBX_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  key: ZBX_SERVER_HOST
                  name: {{.Chart.Name }}-agent
          image: zabbix/{{.Chart.Name }}-agent:alpine-{{ .Chart.AppVersion }}
          name: {{.Chart.Name }}-agent
          resources:
            requests:
              cpu: 100m
              memory: "64M"
            limits:
              cpu: 200m
              memory: 128M
          ports:
            - containerPort: 10050
      hostname: {{.Chart.Name }}-agent
      restartPolicy: Always
