apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{.Chart.Name }}-agent
  name: {{.Chart.Name }}-agent
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: "{{.Chart.Name }}-agent"
      port: 10050
      targetPort: 10050
  selector:
    service: {{.Chart.Name }}-agent
