replicaCount: 1
image:
  pullPolicy: IfNotPresent
  tag: ~
nameOverride: zabbix
fullnameOverride: zabbix
serviceAccount:
  create: true
  annotations: {}
  name: "{{ .Values.fullnameOverride }}"
securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
companyName: MYCOMPANY
domain: mydomain.local
