apiVersion: v1
data:
  PHP_TZ: America/Sao_Paulo
  ENABLE_WEB_ACCESS_LOG: "true"
  ZBX_ENABLE_SNMP_TRAPS: "true"
  ZBX_HOSTNAME: {{ .Chart.Name }}-web
  ZBX_SERVER_NAME: {{  .Value.companyName }}
  ZBX_SERVER_HOST: {{ .Chart.Name }}-server.{{ .Release.Namespace }}.svc.cluster.local
  DB_SERVER_HOST: mariadb.{{ .Release.Namespace }}.svc.cluster.local
  DB_SERVER_PORT: "3306"
  MYSQL_DATABASE: "{{ .Chart.Name }}"
kind: ConfigMap
metadata:
  labels:
    service: {{ .Chart.Name }}
  name: {{ .Chart.Name }}-web
  namespace: {{ .Release.Namespace }}
