apiVersion: v1
kind: Service
metadata:
  annotations:
    com.zabbix.company: {{ .Values.companyName }}
    com.zabbix.component: {{ .Chart.Name }}-web
    com.zabbix.description: Zabbix web
    com.zabbix.os: alpine
  labels:
    service: {{ .Chart.Name }}-web
  name: {{ .Chart.Name }}-web
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: "{{ .Chart.Name }}-web"
      port: 8080
      targetPort: 8080
  selector:
    service: {{ .Chart.Name }}-web
