apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{.Chart.Name }}-mariadb
  name: {{.Chart.Name }}-mariadb
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: "{{.Chart.Name }}-mariadb"
      port: 3306
      targetPort: 3306
  selector:
    service: {{.Chart.Name }}-mariadb
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     service: {{.Chart.Name }}-mariadb
#   name: {{.Chart.Name }}-mariadb-lb
#   namespace: {{ .Release.Namespace }}
# spec:
#   type: LoadBalancer
#   ports:
#     - name: "{{.Chart.Name }}-mariadb-lb-tcp"
#       port: 3306
#       targetPort: 3306
#       protocol: TCP
#   selector:
#     service: {{.Chart.Name }}-mariadb
