apiVersion: v1
data:
  PHP_TZ: America/Sao_Paulo
  ENABLE_WEB_ACCESS_LOG: "true"
  ZBX_ENABLE_SNMP_TRAPS: "true"
  ZBX_HOSTNAME: {{.Chart.Name }}-server
  ZBX_SERVER_NAME: {{ .Values.companyName }}
  ZBX_SERVER_HOST: {{.Chart.Name }}-server.{{ .Release.Namespace }}.svc.cluster.local
  DB_SERVER_HOST: {{.Chart.Name }}-mariadb.{{ .Release.Namespace }}.svc.cluster.local
  DB_SERVER_PORT: "3306"
  MARIADB_DATABASE: "zabbix"
kind: ConfigMap
metadata:
  labels:
    service: zabbix
  name: {{.Chart.Name }}-server
  namespace: {{ .Release.Namespace }}
