apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Chart.Name }}"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  refreshInterval: "30m"
  target:
    name: "{{ .Chart.Name }}"
    deletionPolicy: Retain
  data:
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: k8s/{{ .Chart.Name }}
        property: MYSQL_DATABASE
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: k8s/{{ .Chart.Name }}
        property: MYSQL_PASSWORD
    - secretKey: MYSQL_USER
      remoteRef:
        key: k8s/{{ .Chart.Name }}
        property: MYSQL_USER
